const pagesA = [
    {
        id: 651,
        type: 1,
        kuerzel: "A 0",
        template_file: "",
        kapitel: 1,
        titel: "Übersicht",
        filename: "uebersicht_a",
        printfile: "",
        verweis_titel: "Übersicht",
        mediaquery: 0,
        pagenumber: "0",
    },

    {
        id: 815,
        type: 0,
        kuerzel: "A 1",
        template_file: "",
        kapitel: 1,
        titel: "Physikalisch-technische Grundlagen",
        filename: "",
        printfile: "",
        verweis_titel: "Physikalisch-technische Grundlagen",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 860,
                type: 1,
                kuerzel: "A 1.1",
                template_file: "",
                kapitel: 1,
                titel: "Einleitung",
                filename: "einleitung_a2",
                printfile: "",
                verweis_titel: "Physikalisch-technische Grundlagen - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 652,
                type: 1,
                kuerzel: "A 1.2",
                template_file: "",
                kapitel: 1,
                titel: "Kraft",
                filename: "kraft",
                printfile: "",
                verweis_titel: "Kraft",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 653,
                type: 1,
                kuerzel: "A 1.3",
                template_file: "",
                kapitel: 1,
                titel: "Arbeit und Leistung",
                filename: "arbeit_leistung",
                printfile: "",
                verweis_titel: "Arbeit und Leistung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 654,
                type: 1,
                kuerzel: "A 1.4",
                template_file: "",
                kapitel: 1,
                titel: "Drehmoment",
                filename: "drehmoment",
                printfile: "",
                verweis_titel: "Drehmoment",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 655,
                type: 1,
                kuerzel: "A 1.5",
                template_file: "",
                kapitel: 1,
                titel: "Reibung",
                filename: "reibung",
                printfile: "",
                verweis_titel: "Reibung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 656,
                type: 1,
                kuerzel: "A 1.6",
                template_file: "",
                kapitel: 1,
                titel: "Kinematik",
                filename: "kinematik",
                printfile: "",
                verweis_titel: "Kinematik",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 816,
        type: 0,
        kuerzel: "A 2",
        template_file: "",
        kapitel: 1,
        titel: "Festigkeitslehre",
        filename: "",
        printfile: "",
        verweis_titel: "Festigkeitslehre",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 657,
                type: 1,
                kuerzel: "A 2.1",
                template_file: "",
                kapitel: 1,
                titel: "Einleitung",
                filename: "festigkeitlehre_einleitung",
                printfile: "",
                verweis_titel: "Festigkeitslehre - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 658,
                type: 1,
                kuerzel: "A 2.2",
                template_file: "",
                kapitel: 1,
                titel: "Beanspruchungsarten",
                filename: "beansprungungsarten",
                printfile: "",
                verweis_titel: "Beanspruchungsarten",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 659,
                type: 1,
                kuerzel: "A 2.3",
                template_file: "",
                kapitel: 1,
                titel: "Belastungsfälle",
                filename: "belastungsfaelle",
                printfile: "",
                verweis_titel: "Belastungsfälle",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 660,
                type: 1,
                kuerzel: "A 2.4",
                template_file: "",
                kapitel: 1,
                titel: "Zulässige Spannungen",
                filename: "zulaessige_spannungen",
                printfile: "",
                verweis_titel: "Zulässige Spannungen",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 817,
        type: 0,
        kuerzel: "A 3",
        template_file: "",
        kapitel: 1,
        titel: "Werkstoffe",
        filename: "",
        printfile: "",
        verweis_titel: "Werkstoffe",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 661,
                type: 1,
                kuerzel: "A 3.1",
                template_file: "",
                kapitel: 1,
                titel: "Einleitung",
                filename: "werkstoffe_einleitung",
                printfile: "",
                verweis_titel: "Werkstoffe - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 662,
                type: 1,
                kuerzel: "A 3.2",
                template_file: "",
                kapitel: 1,
                titel: "Einteilung",
                filename: "einteilung",
                printfile: "",
                verweis_titel: "Werkstoffe - Einteilung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 663,
                type: 1,
                kuerzel: "A 3.3",
                template_file: "",
                kapitel: 1,
                titel: "Benennung von Stählen",
                filename: "benennung_staehlen",
                printfile: "",
                verweis_titel: "Benennung von Stählen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 664,
                type: 1,
                kuerzel: "A 3.4",
                template_file: "",
                kapitel: 1,
                titel: "Kennwerte und Prüfverfahren",
                filename: "kennwerte_pruefverfahren",
                printfile: "",
                verweis_titel: "Kennwerte und Prüfverfahren",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 665,
                type: 1,
                kuerzel: "A 3.5",
                template_file: "",
                kapitel: 1,
                titel: "Behandlungszustand",
                filename: "behandlungszustand",
                printfile: "",
                verweis_titel: "Behandlungszustand",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 666,
                type: 1,
                kuerzel: "A 3.6",
                template_file: "",
                kapitel: 1,
                titel: "Wärmebehandung",
                filename: "waermebehandung",
                printfile: "",
                verweis_titel: "Wärmebehandung",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 818,
        type: 0,
        kuerzel: "A 4",
        template_file: "",
        kapitel: 1,
        titel: "Toleranzen",
        filename: "",
        printfile: "",
        verweis_titel: "Toleranzen",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 667,
                type: 1,
                kuerzel: "A 4.1",
                template_file: "",
                kapitel: 1,
                titel: "Einleitung",
                filename: "toleranzen_einleitung",
                printfile: "",
                verweis_titel: "Toleranzen - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 668,
                type: 1,
                kuerzel: "A 4.2",
                template_file: "",
                kapitel: 1,
                titel: "Maßtoleranzen",
                filename: "masstoleranzen",
                printfile: "",
                verweis_titel: "Maßtoleranzen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 669,
                type: 1,
                kuerzel: "A 4.3",
                template_file: "",
                kapitel: 1,
                titel: "Formtoleranzen",
                filename: "formtoleranzen",
                printfile: "",
                verweis_titel: "Formtoleranzen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 670,
                type: 1,
                kuerzel: "A 4.4",
                template_file: "",
                kapitel: 1,
                titel: "Lagetoleranzen",
                filename: "lagetoleranzen",
                printfile: "",
                verweis_titel: "Lagetoleranzen",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 819,
        type: 0,
        kuerzel: "A 5",
        template_file: "",
        kapitel: 1,
        titel: "Passungen",
        filename: "",
        printfile: "",
        verweis_titel: "Passungen",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 671,
                type: 1,
                kuerzel: "A 5.1",
                template_file: "",
                kapitel: 1,
                titel: "Einleitung",
                filename: "passungen_einleitung",
                printfile: "",
                verweis_titel: "Passungen - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 672,
                type: 1,
                kuerzel: "A 5.2",
                template_file: "",
                kapitel: 1,
                titel: "Grundbegriffe",
                filename: "grundbegriffe",
                printfile: "",
                verweis_titel: "Grundbegriffe",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 673,
                type: 1,
                kuerzel: "A 5.3",
                template_file: "",
                kapitel: 1,
                titel: "ISO-Passungssystem",
                filename: "iso-passungssystem",
                printfile: "",
                verweis_titel: "ISO-Passungssystem",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 820,
        type: 0,
        kuerzel: "A 6",
        template_file: "",
        kapitel: 1,
        titel: "Oberflächen",
        filename: "",
        printfile: "",
        verweis_titel: "Oberflächen",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 674,
                type: 1,
                kuerzel: "A 6.1",
                template_file: "",
                kapitel: 1,
                titel: "Einleitung",
                filename: "oberflaechen_einleitung",
                printfile: "",
                verweis_titel: "Oberflächen - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 675,
                type: 1,
                kuerzel: "A 6.2",
                template_file: "",
                kapitel: 1,
                titel: "Form",
                filename: "form",
                printfile: "",
                verweis_titel: "Form",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 676,
                type: 1,
                kuerzel: "A 6.3",
                template_file: "",
                kapitel: 1,
                titel: "Rauheit",
                filename: "rauheit",
                printfile: "",
                verweis_titel: "Rauheit",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 677,
                type: 1,
                kuerzel: "A 6.4",
                template_file: "",
                kapitel: 1,
                titel: "Angabe in Zeichnungen",
                filename: "angabe_zeichnungen",
                printfile: "",
                verweis_titel: "Angabe in Zeichnungen",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 821,
        type: 0,
        kuerzel: "A 7",
        template_file: "",
        kapitel: 1,
        titel: "Prüfen (Lehren und Messen)",
        filename: "",
        printfile: "",
        verweis_titel: "Prüfen (Lehren und Messen)",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 678,
                type: 1,
                kuerzel: "A 7.1",
                template_file: "",
                kapitel: 1,
                titel: "Einleitung",
                filename: "pruefen_einleitung",
                printfile: "",
                verweis_titel: "Prüfen - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 679,
                type: 1,
                kuerzel: "A 7.2",
                template_file: "",
                kapitel: 1,
                titel: "Lehren",
                filename: "lehren",
                printfile: "",
                verweis_titel: "Lehren",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 680,
                type: 1,
                kuerzel: "A 7.3",
                template_file: "",
                kapitel: 1,
                titel: "Messen",
                filename: "messen",
                printfile: "",
                verweis_titel: "Messen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 681,
                type: 1,
                kuerzel: "A 7.4",
                template_file: "",
                kapitel: 1,
                titel: "Fehler beim Prüfen",
                filename: "fehler_pruefen",
                printfile: "",
                verweis_titel: "Fehler beim Prüfen",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 822,
        type: 0,
        kuerzel: "A 8",
        template_file: "",
        kapitel: 1,
        titel: "Arbeits- und Umweltschutz",
        filename: "",
        printfile: "",
        verweis_titel: "Arbeits- und Umweltschutz",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 682,
                type: 1,
                kuerzel: "A 8.1",
                template_file: "",
                kapitel: 1,
                titel: "Einleitung",
                filename: "arbeit_umw_einleitung",
                printfile: "",
                verweis_titel: "Arbeits- und Umweltschutz - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 683,
                type: 1,
                kuerzel: "A 8.2",
                template_file: "",
                kapitel: 1,
                titel: "Persönliche Schutzmaßnahmen",
                filename: "persoenliche_schutzmassnahmen",
                printfile: "",
                verweis_titel: "Persönliche Schutzmaßnahmen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 684,
                type: 1,
                kuerzel: "A 8.3",
                template_file: "",
                kapitel: 1,
                titel: "Unfallverhütungsvorschriften",
                filename: "unfallverhuetungsvorschriften",
                printfile: "",
                verweis_titel: "Unfallverhütungsvorschriften",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 697,
                type: 1,
                kuerzel: "A 8.4",
                template_file: "",
                kapitel: 1,
                titel: "Umweltschutz",
                filename: "umweltschutz",
                printfile: "",
                verweis_titel: "Umweltschutz",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

];
export default pagesA;