const pagesD = [
    {
        id: 865,
        type: 1,
        kuerzel: "D 0",
        template_file: "",
        kapitel: 4,
        titel: "Übersicht",
        filename: "uebersicht_d",
        printfile: "",
        verweis_titel: "Übersicht",
        mediaquery: 0,
        pagenumber: "0",
    },

    {
        id: 843,
        type: 0,
        kuerzel: "D 1",
        template_file: "",
        kapitel: 4,
        titel: "Gehäuse",
        filename: "",
        printfile: "",
        verweis_titel: "Gehäuse",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 781,
                type: 1,
                kuerzel: "D 1.1",
                template_file: "",
                kapitel: 4,
                titel: "Einleitung",
                filename: "einleitung_gehaeuse",
                printfile: "",
                verweis_titel: "Gehäuse - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 782,
                type: 1,
                kuerzel: "D 1.2",
                template_file: "",
                kapitel: 4,
                titel: "Montage und Demontage",
                filename: "montage_demontage",
                printfile: "",
                verweis_titel: "Montage und Demontage",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 783,
                type: 1,
                kuerzel: "D 1.3",
                template_file: "",
                kapitel: 4,
                titel: "Störungen",
                filename: "stoerungen",
                printfile: "",
                verweis_titel: "Störungen",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 844,
        type: 0,
        kuerzel: "D 2",
        template_file: "",
        kapitel: 4,
        titel: "Führungen",
        filename: "",
        printfile: "",
        verweis_titel: "Führungen",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 784,
                type: 1,
                kuerzel: "D 2.1",
                template_file: "",
                kapitel: 4,
                titel: "Einleitung",
                filename: "einleitung_fuehrungen",
                printfile: "",
                verweis_titel: "Führungen - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 785,
                type: 1,
                kuerzel: "D 2.2",
                template_file: "",
                kapitel: 4,
                titel: "Arten von Führungen",
                filename: "arten_fuehrungen",
                printfile: "",
                verweis_titel: "Arten von Führungen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 786,
                type: 1,
                kuerzel: "D 2.3",
                template_file: "",
                kapitel: 4,
                titel: "Montage von Führungen",
                filename: "montage_fuehrungen",
                printfile: "",
                verweis_titel: "Montage von Führungen",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 845,
        type: 0,
        kuerzel: "D 3",
        template_file: "",
        kapitel: 4,
        titel: "Lager",
        filename: "",
        printfile: "",
        verweis_titel: "Lager",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 787,
                type: 1,
                kuerzel: "D 3.1",
                template_file: "",
                kapitel: 4,
                titel: "Einleitung",
                filename: "einleitung_lager",
                printfile: "",
                verweis_titel: "Lager - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 788,
                type: 1,
                kuerzel: "D 3.2",
                template_file: "",
                kapitel: 4,
                titel: "Einteilung der Lager",
                filename: "einteilung_lager",
                printfile: "",
                verweis_titel: "Einteilung der Lager",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 846,
        type: 0,
        kuerzel: "D 4",
        template_file: "",
        kapitel: 4,
        titel: "Wälzlager",
        filename: "",
        printfile: "",
        verweis_titel: "Wälzlager",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 789,
                type: 1,
                kuerzel: "D 4.1",
                template_file: "",
                kapitel: 4,
                titel: "Einleitung",
                filename: "einleitung_waelzlager",
                printfile: "",
                verweis_titel: "Wälzlager - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 790,
                type: 1,
                kuerzel: "D 4.2",
                template_file: "",
                kapitel: 4,
                titel: "Wälzlagerarten",
                filename: "waelzlagerarten",
                printfile: "",
                verweis_titel: "Wälzlagerarten",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 791,
                type: 1,
                kuerzel: "D 4.3",
                template_file: "",
                kapitel: 4,
                titel: "Auswahlkriterien für Wälzlager",
                filename: "auswahl_waelzlager",
                printfile: "",
                verweis_titel: "Auswahlkriterien für Wälzlager",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 792,
                type: 1,
                kuerzel: "D 4.4",
                template_file: "",
                kapitel: 4,
                titel: "Ein- und Ausbau",
                filename: "einbau_waelzlager",
                printfile: "",
                verweis_titel: "Ein- und Ausbau",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 793,
                type: 1,
                kuerzel: "D 4.5",
                template_file: "",
                kapitel: 4,
                titel: "Montagefehler",
                filename: "montage_waelzlager",
                printfile: "",
                verweis_titel: "Montagefehler",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 847,
        type: 0,
        kuerzel: "D 5",
        template_file: "",
        kapitel: 4,
        titel: "Gleitlager",
        filename: "",
        printfile: "",
        verweis_titel: "Gleitlager",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 794,
                type: 1,
                kuerzel: "D 5.1",
                template_file: "",
                kapitel: 4,
                titel: "Einleitung",
                filename: "einleitung_gleitlager",
                printfile: "",
                verweis_titel: "Gleitlager - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 795,
                type: 1,
                kuerzel: "D 5.2",
                template_file: "",
                kapitel: 4,
                titel: "Einsatzgebiete und Werkstoffe",
                filename: "einsatzgebiet_gleitlager",
                printfile: "",
                verweis_titel: "Einsatzgebiete und Werkstoffe",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 796,
                type: 1,
                kuerzel: "D 5.3",
                template_file: "",
                kapitel: 4,
                titel: "Montage",
                filename: "montage_gleitlager",
                printfile: "",
                verweis_titel: "Montage",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 797,
                type: 1,
                kuerzel: "D 5.4",
                template_file: "",
                kapitel: 4,
                titel: "Fehler",
                filename: "fehler_gleitlager",
                printfile: "",
                verweis_titel: "Fehler",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 848,
        type: 0,
        kuerzel: "D 6",
        template_file: "",
        kapitel: 4,
        titel: "Schmierung",
        filename: "",
        printfile: "",
        verweis_titel: "Schmierung",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 798,
                type: 1,
                kuerzel: "D 6.1",
                template_file: "",
                kapitel: 4,
                titel: "Einleitung",
                filename: "einleitung_schmierung",
                printfile: "",
                verweis_titel: "Schmierung - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 799,
                type: 1,
                kuerzel: "D 6.2",
                template_file: "",
                kapitel: 4,
                titel: "Schmierung von Wälzlagern",
                filename: "schmierung_waelzlager",
                printfile: "",
                verweis_titel: "Schmierung von Wälzlagern",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 800,
                type: 1,
                kuerzel: "D 6.3",
                template_file: "",
                kapitel: 4,
                titel: "Schmierung von Gleitlagern",
                filename: "schmierung_gleitlager",
                printfile: "",
                verweis_titel: "Schmierung von Gleitlagern",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 801,
                type: 1,
                kuerzel: "D 6.4",
                template_file: "",
                kapitel: 4,
                titel: "Schmierstoffe",
                filename: "schmierstoffe",
                printfile: "",
                verweis_titel: "Schmierstoffe",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 802,
                type: 1,
                kuerzel: "D 6.5",
                template_file: "",
                kapitel: 4,
                titel: "Fehler bei der Schmierung",
                filename: "fehler_schmierung",
                printfile: "",
                verweis_titel: "Fehler bei der Schmierung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 803,
                type: 1,
                kuerzel: "D 6.6",
                template_file: "",
                kapitel: 4,
                titel: "Entsorgung",
                filename: "entsorgung",
                printfile: "",
                verweis_titel: "Entsorgung",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 849,
        type: 0,
        kuerzel: "D 7",
        template_file: "",
        kapitel: 4,
        titel: "Dichtung",
        filename: "",
        printfile: "",
        verweis_titel: "Dichtung",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 804,
                type: 1,
                kuerzel: "D 7.1",
                template_file: "",
                kapitel: 4,
                titel: "Einleitung",
                filename: "einleitung_dichtungen",
                printfile: "",
                verweis_titel: "Dichtung - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 805,
                type: 1,
                kuerzel: "D 7.2",
                template_file: "",
                kapitel: 4,
                titel: "Dichtungen an ruhenden Flächen",
                filename: "dichtungen_ruhend",
                printfile: "",
                verweis_titel: "Dichtungen an ruhenden Flächen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 806,
                type: 1,
                kuerzel: "D 7.3",
                template_file: "",
                kapitel: 4,
                titel: "Dichtungen an bewegten Flächen",
                filename: "dichtungen_bewegt",
                printfile: "",
                verweis_titel: "Dichtungen an bewegten Flächen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 807,
                type: 1,
                kuerzel: "D 7.4",
                template_file: "",
                kapitel: 4,
                titel: "Montage",
                filename: "montage_dichtung",
                printfile: "",
                verweis_titel: "Montage",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 808,
                type: 1,
                kuerzel: "D 7.5",
                template_file: "",
                kapitel: 4,
                titel: "Fehler bei der Montage",
                filename: "fehler_dichtung",
                printfile: "",
                verweis_titel: "Fehler bei der Montage",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 850,
        type: 0,
        kuerzel: "D 8",
        template_file: "",
        kapitel: 4,
        titel: "Achsen",
        filename: "",
        printfile: "",
        verweis_titel: "Achsen",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 809,
                type: 1,
                kuerzel: "D 8.1",
                template_file: "",
                kapitel: 4,
                titel: "Einleitung",
                filename: "einleitung_achsen",
                printfile: "",
                verweis_titel: "Achsen - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 810,
                type: 1,
                kuerzel: "D 8.2",
                template_file: "",
                kapitel: 4,
                titel: "Biegemoment",
                filename: "biegemoment",
                printfile: "",
                verweis_titel: "Biegemoment",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

];
export default pagesD;
