const pagesB = [
    {
        id: 863,
        type: 1,
        kuerzel: "B 0",
        template_file: "",
        kapitel: 2,
        titel: "Übersicht",
        filename: "uebersicht_b",
        printfile: "",
        verweis_titel: "Übersicht",
        mediaquery: 0,
        pagenumber: "0",
    },

    {
        id: 826,
        type: 0,
        kuerzel: "B 1",
        template_file: "",
        kapitel: 2,
        titel: "Fügeverfahren nach DIN",
        filename: "",
        printfile: "",
        verweis_titel: "Fügeverfahren nach DIN",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 698,
                type: 1,
                kuerzel: "B 1.1",
                template_file: "",
                kapitel: 2,
                titel: "Einleitung",
                filename: "einleitung_fuegeverfahren",
                printfile: "",
                verweis_titel: "Fügeverfahren nach DIN - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 699,
                type: 1,
                kuerzel: "B 1.2",
                template_file: "",
                kapitel: 2,
                titel: "Fertigungsverfahren",
                filename: "fertigungsverfahren",
                printfile: "",
                verweis_titel: "Fertigungsverfahren",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 827,
        type: 0,
        kuerzel: "B 2",
        template_file: "",
        kapitel: 2,
        titel: "Verbindungsarten",
        filename: "",
        printfile: "",
        verweis_titel: "Verbindungsarten",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 700,
                type: 1,
                kuerzel: "B 2.1",
                template_file: "",
                kapitel: 2,
                titel: "Einleitung",
                filename: "einleitung_verbindungsarten",
                printfile: "",
                verweis_titel: "Verbindungsarten - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 701,
                type: 1,
                kuerzel: "B 2.2",
                template_file: "",
                kapitel: 2,
                titel: "Kraft-, Form-, Stoffschluss",
                filename: "kraftschluss",
                printfile: "",
                verweis_titel: "Kraft-, Form-, Stoffschluss",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 702,
                type: 1,
                kuerzel: "B 2.3",
                template_file: "",
                kapitel: 2,
                titel: "Lösbar, unlösbar",
                filename: "loesbar",
                printfile: "",
                verweis_titel: "Lösbar, unlösbar",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 828,
        type: 0,
        kuerzel: "B 3",
        template_file: "",
        kapitel: 2,
        titel: "Schrauben und Muttern",
        filename: "",
        printfile: "",
        verweis_titel: "Schrauben und Muttern",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 703,
                type: 1,
                kuerzel: "B 3.1",
                template_file: "",
                kapitel: 2,
                titel: "Einleitung",
                filename: "einleitung_schrauben",
                printfile: "",
                verweis_titel: "Schrauben und Muttern - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 704,
                type: 1,
                kuerzel: "B 3.2",
                template_file: "",
                kapitel: 2,
                titel: "Gewindearten",
                filename: "gewindearten",
                printfile: "",
                verweis_titel: "Gewindearten",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 705,
                type: 1,
                kuerzel: "B 3.3",
                template_file: "",
                kapitel: 2,
                titel: "Bezeichnungen am Gewinde",
                filename: "bezeichnungen_gewinde",
                printfile: "",
                verweis_titel: "Bezeichnungen am Gewinde",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 706,
                type: 1,
                kuerzel: "B 3.4",
                template_file: "",
                kapitel: 2,
                titel: "Kräfte am Gewinde",
                filename: "kraft_gewinde",
                printfile: "",
                verweis_titel: "Kräfte am Gewinde",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 707,
                type: 1,
                kuerzel: "B 3.5",
                template_file: "",
                kapitel: 2,
                titel: "Schraubenarten",
                filename: "schraubenarten",
                printfile: "",
                verweis_titel: "Schraubenarten",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 708,
                type: 1,
                kuerzel: "B 3.6",
                template_file: "",
                kapitel: 2,
                titel: "Mutternarten",
                filename: "mutternarten",
                printfile: "",
                verweis_titel: "Mutternarten",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 829,
        type: 0,
        kuerzel: "B 4",
        template_file: "",
        kapitel: 2,
        titel: "Schraubenverbindungen",
        filename: "",
        printfile: "",
        verweis_titel: "Schraubenverbindungen",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 709,
                type: 1,
                kuerzel: "B 4.1",
                template_file: "",
                kapitel: 2,
                titel: "Einleitung",
                filename: "einleitung_schraubenverbindungen",
                printfile: "",
                verweis_titel: "Schraubenverbindungen - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 710,
                type: 1,
                kuerzel: "B 4.2",
                template_file: "",
                kapitel: 2,
                titel: "Wirkungsweise",
                filename: "wirkungsweise",
                printfile: "",
                verweis_titel: "Wirkungsweise",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 711,
                type: 1,
                kuerzel: "B 4.3",
                template_file: "",
                kapitel: 2,
                titel: "Bauformen",
                filename: "bauformen",
                printfile: "",
                verweis_titel: "Bauformen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 712,
                type: 1,
                kuerzel: "B 4.4",
                template_file: "",
                kapitel: 2,
                titel: "Scheiben",
                filename: "scheiben",
                printfile: "",
                verweis_titel: "Scheiben",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 713,
                type: 1,
                kuerzel: "B 4.5",
                template_file: "",
                kapitel: 2,
                titel: "Schraubensicherungen",
                filename: "schraubensicherungen",
                printfile: "",
                verweis_titel: "Schraubensicherungen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 714,
                type: 1,
                kuerzel: "B 4.6",
                template_file: "",
                kapitel: 2,
                titel: "Herstellen von Gewinden",
                filename: "herstellen_gewinden",
                printfile: "",
                verweis_titel: "Herstellen von Gewinden",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 715,
                type: 1,
                kuerzel: "B 4.7",
                template_file: "",
                kapitel: 2,
                titel: "Montage und Werkzeuge",
                filename: "montage_werkzeuge",
                printfile: "",
                verweis_titel: "Montage und Werkzeuge",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 716,
                type: 1,
                kuerzel: "B 4.8",
                template_file: "",
                kapitel: 2,
                titel: "Fehler und Fehlerbeseitigung",
                filename: "fehler_schrauben",
                printfile: "",
                verweis_titel: "Fehler und Fehlerbeseitigung",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 830,
        type: 0,
        kuerzel: "B 5",
        template_file: "",
        kapitel: 2,
        titel: "Bolzen- und Stiftverbindungen",
        filename: "",
        printfile: "",
        verweis_titel: "Bolzen- und Stiftverbindungen",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 717,
                type: 1,
                kuerzel: "B 5.1",
                template_file: "",
                kapitel: 2,
                titel: "Einleitung",
                filename: "bolzen_einleitung",
                printfile: "",
                verweis_titel: "Bolzen- und Stiftverbindungen - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 718,
                type: 1,
                kuerzel: "B 5.2",
                template_file: "",
                kapitel: 2,
                titel: "Formen der Bolzen und Stifte",
                filename: "formen_bolzen",
                printfile: "",
                verweis_titel: "Formen der Bolzen und Stifte",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 719,
                type: 1,
                kuerzel: "B 5.3",
                template_file: "",
                kapitel: 2,
                titel: "Herstellen der Verbindung",
                filename: "herstellen_verbindung",
                printfile: "",
                verweis_titel: "Herstellen der Verbindung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 720,
                type: 1,
                kuerzel: "B 5.4",
                template_file: "",
                kapitel: 2,
                titel: "Fehler und Fehlerbeseitigung",
                filename: "fehler_bolzen",
                printfile: "",
                verweis_titel: "Fehler und Fehlerbeseitigung",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 831,
        type: 0,
        kuerzel: "B 6",
        template_file: "",
        kapitel: 2,
        titel: "Sicherungselemente",
        filename: "",
        printfile: "",
        verweis_titel: "Sicherungselemente",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 721,
                type: 1,
                kuerzel: "B 6.1",
                template_file: "",
                kapitel: 2,
                titel: "Einleitung",
                filename: "einleitung_sicherung",
                printfile: "",
                verweis_titel: "Sicherungselemente - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 722,
                type: 1,
                kuerzel: "B 6.2",
                template_file: "",
                kapitel: 2,
                titel: "Arten und Bauformen",
                filename: "arten_sicherung",
                printfile: "",
                verweis_titel: "Arten und Bauformen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 723,
                type: 1,
                kuerzel: "B 6.3",
                template_file: "",
                kapitel: 2,
                titel: "Montage und Werkzeuge",
                filename: "montage_sicherung",
                printfile: "",
                verweis_titel: "Montage und Werkzeuge",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 724,
                type: 1,
                kuerzel: "B 6.4",
                template_file: "",
                kapitel: 2,
                titel: "Fehler und Fehlerbeseitigung",
                filename: "fehler_sicherung",
                printfile: "",
                verweis_titel: "Fehler und Fehlerbeseitigung",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 832,
        type: 0,
        kuerzel: "B 7",
        template_file: "",
        kapitel: 2,
        titel: "Welle-Nabe-Verbindungen",
        filename: "",
        printfile: "",
        verweis_titel: "Welle-Nabe-Verbindungen",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 725,
                type: 1,
                kuerzel: "B 7.1",
                template_file: "",
                kapitel: 2,
                titel: "Einleitung",
                filename: "einleitung_welle",
                printfile: "",
                verweis_titel: "Welle-Nabe-Verbindungen - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 726,
                type: 1,
                kuerzel: "B 7.2",
                template_file: "",
                kapitel: 2,
                titel: "Passfedern",
                filename: "passfedern",
                printfile: "",
                verweis_titel: "Passfedern",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 727,
                type: 1,
                kuerzel: "B 7.3",
                template_file: "",
                kapitel: 2,
                titel: "Keile",
                filename: "keile",
                printfile: "",
                verweis_titel: "Keile",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 728,
                type: 1,
                kuerzel: "B 7.4",
                template_file: "",
                kapitel: 2,
                titel: "Kegelverbindungen",
                filename: "kegel",
                printfile: "",
                verweis_titel: "Kegelverbindungen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 729,
                type: 1,
                kuerzel: "B 7.5",
                template_file: "",
                kapitel: 2,
                titel: "Montage und Werkzeuge",
                filename: "montage_welle",
                printfile: "",
                verweis_titel: "Montage und Werkzeuge",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 730,
                type: 1,
                kuerzel: "B 7.6",
                template_file: "",
                kapitel: 2,
                titel: "Fehler und Fehlerbeseitigung",
                filename: "fehler_welle",
                printfile: "",
                verweis_titel: "Fehler und Fehlerbeseitigung",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 833,
        type: 0,
        kuerzel: "B 8",
        template_file: "",
        kapitel: 2,
        titel: "Press- und Schnappverbindungen",
        filename: "",
        printfile: "",
        verweis_titel: "Press- und Schnappverbindungen",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 731,
                type: 1,
                kuerzel: "B 8.1",
                template_file: "",
                kapitel: 2,
                titel: "Einleitung",
                filename: "einleitung_press",
                printfile: "",
                verweis_titel: "Einleitung - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 732,
                type: 1,
                kuerzel: "B 8.2",
                template_file: "",
                kapitel: 2,
                titel: "Pressverbindungen",
                filename: "pressverbindungen",
                printfile: "",
                verweis_titel: "Pressverbindungen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 733,
                type: 1,
                kuerzel: "B 8.3",
                template_file: "",
                kapitel: 2,
                titel: "Schnappverbindungen",
                filename: "schnappverbindungen",
                printfile: "",
                verweis_titel: "Schnappverbindungen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 734,
                type: 1,
                kuerzel: "B 8.4",
                template_file: "",
                kapitel: 2,
                titel: "Montage und Werkzeuge",
                filename: "montage_press",
                printfile: "",
                verweis_titel: "Montage und Werkzeuge",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 735,
                type: 1,
                kuerzel: "B 8.5",
                template_file: "",
                kapitel: 2,
                titel: "Fehler und Fehlerbeseitigung",
                filename: "fehler_press",
                printfile: "",
                verweis_titel: "Fehler und Fehlerbeseitigung",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 834,
        type: 0,
        kuerzel: "B 9",
        template_file: "",
        kapitel: 2,
        titel: "Klebeverbindungen",
        filename: "",
        printfile: "",
        verweis_titel: "Klebeverbindungen",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 736,
                type: 1,
                kuerzel: "B 9.1",
                template_file: "",
                kapitel: 2,
                titel: "Einleitung",
                filename: "einleitung_kleb",
                printfile: "",
                verweis_titel: "Klebeverbindungen - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 737,
                type: 1,
                kuerzel: "B 9.2",
                template_file: "",
                kapitel: 2,
                titel: "Grundbegriffe",
                filename: "grundbegriffe_kleb",
                printfile: "",
                verweis_titel: "Grundbegriffe",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 738,
                type: 1,
                kuerzel: "B 9.3",
                template_file: "",
                kapitel: 2,
                titel: "Einteilung der Klebstoffe",
                filename: "einteilung_kleb",
                printfile: "",
                verweis_titel: "Einteilung der Klebstoffe",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 739,
                type: 1,
                kuerzel: "B 9.4",
                template_file: "",
                kapitel: 2,
                titel: "Wirkprinzip und Eigenschaften",
                filename: "wirkprinzip",
                printfile: "",
                verweis_titel: "Wirkprinzip und Eigenschaften",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 740,
                type: 1,
                kuerzel: "B 9.5",
                template_file: "",
                kapitel: 2,
                titel: "Montage",
                filename: "montage",
                printfile: "",
                verweis_titel: "Montage",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 741,
                type: 1,
                kuerzel: "B 9.6",
                template_file: "",
                kapitel: 2,
                titel: "Fehler und Fehlerbeseitigung",
                filename: "fehler_kleb",
                printfile: "",
                verweis_titel: "Fehler und Fehlerbeseitigung",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

];
export default pagesB;