const pagesC = [
    {
        id: 864,
        type: 1,
        kuerzel: "C 0",
        template_file: "",
        kapitel: 3,
        titel: "Übersicht",
        filename: "uebersicht_c",
        printfile: "",
        verweis_titel: "Übersicht",
        mediaquery: 0,
        pagenumber: "0",
    },

    {
        id: 835,
        type: 0,
        kuerzel: "C 1",
        template_file: "",
        kapitel: 3,
        titel: "Systeme zum Energieumsatz",
        filename: "",
        printfile: "",
        verweis_titel: "Systeme zum Energieumsatz",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 742,
                type: 1,
                kuerzel: "C 1.1",
                template_file: "",
                kapitel: 3,
                titel: "Einleitung",
                filename: "einleitung_energieumsatz",
                printfile: "",
                verweis_titel: "Systeme zum Energieumsatz - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 743,
                type: 1,
                kuerzel: "C 1.2",
                template_file: "",
                kapitel: 3,
                titel: "Maschinen als technische Systeme",
                filename: "maschinen",
                printfile: "",
                verweis_titel: "Maschinen als technische Systeme",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 744,
                type: 1,
                kuerzel: "C 1.3",
                template_file: "",
                kapitel: 3,
                titel: "Unterteilung technischer Systeme",
                filename: "unterteilung",
                printfile: "",
                verweis_titel: "Unterteilung technischer Systeme",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 745,
                type: 1,
                kuerzel: "C 1.4",
                template_file: "",
                kapitel: 3,
                titel: "Beispiel: Werkzeugmaschine",
                filename: "werkzeugmaschine",
                printfile: "",
                verweis_titel: "Beispiel: Werkzeugmaschine",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 836,
        type: 0,
        kuerzel: "C 2",
        template_file: "",
        kapitel: 3,
        titel: "Kupplungen",
        filename: "",
        printfile: "",
        verweis_titel: "Kupplungen",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 746,
                type: 1,
                kuerzel: "C 2.1",
                template_file: "",
                kapitel: 3,
                titel: "Einleitung",
                filename: "einleitung_kupplungen",
                printfile: "",
                verweis_titel: "Kupplungen - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 747,
                type: 1,
                kuerzel: "C 2.2",
                template_file: "",
                kapitel: 3,
                titel: "Schaltbare Kupplungen",
                filename: "schaltbar",
                printfile: "",
                verweis_titel: "Schaltbare Kupplungen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 748,
                type: 1,
                kuerzel: "C 2.3",
                template_file: "",
                kapitel: 3,
                titel: "Nicht schaltbare Kupplungen",
                filename: "nicht_schaltbar",
                printfile: "",
                verweis_titel: "Nicht schaltbare Kupplungen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 749,
                type: 1,
                kuerzel: "C 2.4",
                template_file: "",
                kapitel: 3,
                titel: "Auswahl einer Kupplung",
                filename: "auswahl_kupplung",
                printfile: "",
                verweis_titel: "Auswahl einer Kupplung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 750,
                type: 1,
                kuerzel: "C 2.5",
                template_file: "",
                kapitel: 3,
                titel: "Allgemeine Montagetipps",
                filename: "montagetipps",
                printfile: "",
                verweis_titel: "Allgemeine Montagetipps",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 837,
        type: 0,
        kuerzel: "C 3",
        template_file: "",
        kapitel: 3,
        titel: "Getriebe",
        filename: "",
        printfile: "",
        verweis_titel: "Getriebe",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 751,
                type: 1,
                kuerzel: "C 3.1",
                template_file: "",
                kapitel: 3,
                titel: "Einleitung",
                filename: "einleitung_getriebe",
                printfile: "",
                verweis_titel: "Getriebe - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 752,
                type: 1,
                kuerzel: "C 3.2",
                template_file: "",
                kapitel: 3,
                titel: "Getriebearten",
                filename: "getriebearten",
                printfile: "",
                verweis_titel: "Getriebearten",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 753,
                type: 1,
                kuerzel: "C 3.3",
                template_file: "",
                kapitel: 3,
                titel: "Kenngrößen",
                filename: "kenngroessen",
                printfile: "",
                verweis_titel: "Kenngrößen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 754,
                type: 1,
                kuerzel: "C 3.4",
                template_file: "",
                kapitel: 3,
                titel: "Beispiel: Kenngrößen",
                filename: "bsp_kenngroessen",
                printfile: "",
                verweis_titel: "Beispiel: Kenngrößen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 755,
                type: 1,
                kuerzel: "C 3.5",
                template_file: "",
                kapitel: 3,
                titel: "Montage, Wartung, Fehler",
                filename: "montage_getriebe",
                printfile: "",
                verweis_titel: "Montage, Wartung, Fehler",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 838,
        type: 0,
        kuerzel: "C 4",
        template_file: "",
        kapitel: 3,
        titel: "Zahnräder",
        filename: "",
        printfile: "",
        verweis_titel: "Zahnräder",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 756,
                type: 1,
                kuerzel: "C 4.1",
                template_file: "",
                kapitel: 3,
                titel: "Einleitung",
                filename: "einleitung_zahnraeder",
                printfile: "",
                verweis_titel: "Zahnräder - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 757,
                type: 1,
                kuerzel: "C 4.2",
                template_file: "",
                kapitel: 3,
                titel: "Zahnprofile",
                filename: "zahnprofile",
                printfile: "",
                verweis_titel: "Zahnprofile",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 758,
                type: 1,
                kuerzel: "C 4.3",
                template_file: "",
                kapitel: 3,
                titel: "Verzahnungsarten",
                filename: "verzahnungsarten",
                printfile: "",
                verweis_titel: "Verzahnungsarten",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 759,
                type: 1,
                kuerzel: "C 4.4",
                template_file: "",
                kapitel: 3,
                titel: "Getriebe",
                filename: "getriebe",
                printfile: "",
                verweis_titel: "Getriebe",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 760,
                type: 1,
                kuerzel: "C 4.5",
                template_file: "",
                kapitel: 3,
                titel: "Berechnungsbeispiel",
                filename: "berechnungsbeispiel",
                printfile: "",
                verweis_titel: "Berechnungsbeispiel",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 761,
                type: 1,
                kuerzel: "C 4.6",
                template_file: "",
                kapitel: 3,
                titel: "Profilverschiebung",
                filename: "profilverschiebung",
                printfile: "",
                verweis_titel: "Profilverschiebung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 762,
                type: 1,
                kuerzel: "C 4.7",
                template_file: "",
                kapitel: 3,
                titel: "Werkstoffe",
                filename: "werkstoffe",
                printfile: "",
                verweis_titel: "Werkstoffe",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 839,
        type: 0,
        kuerzel: "C 5",
        template_file: "",
        kapitel: 3,
        titel: "Zahnradgetriebe",
        filename: "",
        printfile: "",
        verweis_titel: "Zahnradgetriebe",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 763,
                type: 1,
                kuerzel: "C 5.1",
                template_file: "",
                kapitel: 3,
                titel: "Einleitung",
                filename: "einleitung_zahngetriebe",
                printfile: "",
                verweis_titel: "Zahnradgetriebe - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 764,
                type: 1,
                kuerzel: "C 5.2",
                template_file: "",
                kapitel: 3,
                titel: "Stirnradgetriebe",
                filename: "stirnradgetriebe",
                printfile: "",
                verweis_titel: "Stirnradgetriebe",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 765,
                type: 1,
                kuerzel: "C 5.3",
                template_file: "",
                kapitel: 3,
                titel: "Kegelradgetriebe",
                filename: "kegelradgetriebe",
                printfile: "",
                verweis_titel: "Kegelradgetriebe",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 766,
                type: 1,
                kuerzel: "C 5.4",
                template_file: "",
                kapitel: 3,
                titel: "Schneckenradgetriebe",
                filename: "schneckenradgetriebe",
                printfile: "",
                verweis_titel: "Schneckenradgetriebe",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 767,
                type: 1,
                kuerzel: "C 5.5",
                template_file: "",
                kapitel: 3,
                titel: "Schmierung",
                filename: "schmierung",
                printfile: "",
                verweis_titel: "Schmierung",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 840,
        type: 0,
        kuerzel: "C 6",
        template_file: "",
        kapitel: 3,
        titel: "Zugmitteltriebe",
        filename: "",
        printfile: "",
        verweis_titel: "Zugmitteltriebe",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 768,
                type: 1,
                kuerzel: "C 6.1",
                template_file: "",
                kapitel: 3,
                titel: "Einleitung",
                filename: "einleitung_zugmitteltriebe",
                printfile: "",
                verweis_titel: "Zugmitteltriebe - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 769,
                type: 1,
                kuerzel: "C 6.2",
                template_file: "",
                kapitel: 3,
                titel: "Formschlüssige Triebe",
                filename: "formschluessig",
                printfile: "",
                verweis_titel: "Formschlüssige Triebe",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 770,
                type: 1,
                kuerzel: "C 6.3",
                template_file: "",
                kapitel: 3,
                titel: "Kraftschlüssige Triebe",
                filename: "kraftschluessig",
                printfile: "",
                verweis_titel: "Kraftschlüssige Triebe",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 771,
                type: 1,
                kuerzel: "C 6.4",
                template_file: "",
                kapitel: 3,
                titel: "Vergleich der Bauformen",
                filename: "vergleich_bauformen",
                printfile: "",
                verweis_titel: "Vergleich der Bauformen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 772,
                type: 1,
                kuerzel: "C 6.5",
                template_file: "",
                kapitel: 3,
                titel: "Schmierung und Wartung",
                filename: "schmierung_wartung",
                printfile: "",
                verweis_titel: "Schmierung und Wartung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 773,
                type: 1,
                kuerzel: "C 6.6",
                template_file: "",
                kapitel: 3,
                titel: "Montage",
                filename: "montage_zugmitteltriebe",
                printfile: "",
                verweis_titel: "Montage",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 841,
        type: 0,
        kuerzel: "C 7",
        template_file: "",
        kapitel: 3,
        titel: "Wellen",
        filename: "",
        printfile: "",
        verweis_titel: "Wellen",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 774,
                type: 1,
                kuerzel: "C 7.1",
                template_file: "",
                kapitel: 3,
                titel: "Einleitung",
                filename: "einleitung_welle",
                printfile: "",
                verweis_titel: "Wellen - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 775,
                type: 1,
                kuerzel: "C 7.2",
                template_file: "",
                kapitel: 3,
                titel: "Belastungen",
                filename: "belastungen",
                printfile: "",
                verweis_titel: "Belastungen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 776,
                type: 1,
                kuerzel: "C 7.3",
                template_file: "",
                kapitel: 3,
                titel: "Bauformen",
                filename: "bauformen_welle",
                printfile: "",
                verweis_titel: "Bauformen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 777,
                type: 1,
                kuerzel: "C 7.4",
                template_file: "",
                kapitel: 3,
                titel: "Montage, Wartung, Fehler",
                filename: "montage_welle",
                printfile: "",
                verweis_titel: "Montage, Wartung, Fehler",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

    {
        id: 842,
        type: 0,
        kuerzel: "C 8",
        template_file: "",
        kapitel: 3,
        titel: "Federn",
        filename: "",
        printfile: "",
        verweis_titel: "Federn",
        mediaquery: 0,
        pagenumber: "0", pages: [

            {
                id: 778,
                type: 1,
                kuerzel: "C 8.1",
                template_file: "",
                kapitel: 3,
                titel: "Einleitung",
                filename: "einleitung_federn",
                printfile: "",
                verweis_titel: "Federn - Einleitung",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 779,
                type: 1,
                kuerzel: "C 8.2",
                template_file: "",
                kapitel: 3,
                titel: "Kenngrößen",
                filename: "kenngroessen_federn",
                printfile: "",
                verweis_titel: "Kenngrößen",
                mediaquery: 0,
                pagenumber: "0",
            },

            {
                id: 780,
                type: 1,
                kuerzel: "C 8.3",
                template_file: "",
                kapitel: 3,
                titel: "Montage, Wartung, Fehler",
                filename: "montage_federn",
                printfile: "",
                verweis_titel: "Montage, Wartung, Fehler",
                mediaquery: 0,
                pagenumber: "0",
            }]
    },

];

export default pagesC;